version: "3.8"

services:
  api:
    build: .
    container_name: api
    ports:
      - ${PORT}:3333
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_BASE_URL: ${API_BASE_URL}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      PORT: ${PORT}
