apiVersion: v1
kind: Secret
metadata:
  name: enviroment
type: Opaque
data:
  database_url: ZmlsZTouL2Rldi5kYg==
  api_base_url: aHR0cDovL2xvY2FsaG9zdDozMzMz
  frontend_base_url: aHR0cDovL2xvY2FsaG9zdDozMDAw
  port: MzMzMw==
