name: CI

on: 
  push:
    branches:
      - main

jobs: 
  build-and-push:
    name: 'Build an push'
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Build docker image
      run: docker build -t mangareira/nlw.teste.api:v1 .